"use strict";
exports.__esModule = true;
exports.FASTEST = exports.SLOWEST = exports.MARGIN = exports.LENGTH = exports.SIZE = exports.keys = void 0;
var keys;
(function (keys) {
    keys[keys["RETURN"] = 13] = "RETURN";
    keys[keys["SPACE"] = 32] = "SPACE";
    keys[keys["LEFT"] = 37] = "LEFT";
    keys[keys["UP"] = 38] = "UP";
    keys[keys["RIGHT"] = 39] = "RIGHT";
    keys[keys["DOWN"] = 40] = "DOWN";
    keys[keys["C"] = 67] = "C";
    keys[keys["G"] = 71] = "G";
    keys[keys["J"] = 74] = "J";
    keys[keys["K"] = 75] = "K";
})(keys = exports.keys || (exports.keys = {}));
exports.SIZE = 40;
exports.LENGTH = 6;
exports.MARGIN = 60;
exports.SLOWEST = 250;
exports.FASTEST = 0;
